"""Argparse dest classification for the read census (#1132 PR 6b).

DATA ONLY. `OUT` = the option changes what a read verb selects or prints;
`INE` = it is a write payload, a plumbing flag or a stamp. Codes: R1 selects
the bucket/slug/data root read; R2 names or binds the record whose text/state
is printed; R3 dry-run prints what would be acted on; R4 selects or formats
what a read verb prints; R5 server plumbing, no content; R6 caller-supplied
write payload; X-HUMAN stamps the authority channel (exemption HUMAN_CHANNEL).
"""

DESTS = {
    "serialize": {
        "transcript": ("INE", "R6"),
        "project": ("OUT", "R1"),
        "session": ("INE", "R6"),
    },
    "write-checkpoint": {
        "project": ("OUT", "R1"),
        "source": ("INE", "R6"),
        "session": ("INE", "R6"),
    },
    "brief": {
        "project": ("OUT", "R1"),
        "team": ("OUT", "R4"),
        "slug": ("OUT", "R1"),
        "global_fallback": ("OUT", "R4"),
        "auto": ("OUT", "R4"),
    },
    "anchor": {
        "file": ("OUT", "R4"),
        "symbol": ("OUT", "R4"),
        "project": ("OUT", "R1"),
        "attach": ("OUT", "R4"),
    },
    "recall": {
        "query": ("OUT", "R4"),
        "project": ("OUT", "R1"),
        "all_projects": ("OUT", "R4"),
        "slug": ("OUT", "R1"),
        "json": ("OUT", "R4"),
        "limit": ("OUT", "R4"),
    },
    "why": {
        "item_id": ("OUT", "R2"),
        "source": ("OUT", "R4"),
        "json": ("OUT", "R4"),
        "project": ("OUT", "R1"),
        "slug": ("OUT", "R1"),
    },
    "diff": {
        "frm": ("OUT", "R4"),
        "to": ("OUT", "R4"),
        "json": ("OUT", "R4"),
        "project": ("OUT", "R1"),
        "slug": ("OUT", "R1"),
    },
    "blame": {
        "item_id": ("OUT", "R2"),
        "json": ("OUT", "R4"),
        "project": ("OUT", "R1"),
        "slug": ("OUT", "R1"),
    },
    "serve": {
        "data_dir": ("OUT", "R1"),
        "project_dir": ("OUT", "R1"),
        "port": ("INE", "R5"),
        "no_browser": ("INE", "R5"),
    },
    "projects": {
        "project": ("OUT", "R1"),
        "json": ("OUT", "R4"),
    },
    "bucket migrate": {
        "project": ("OUT", "R1"),
        "dry_run": ("OUT", "R3"),
        "json": ("INE", "R6"),
    },
    "slug": {
        "path": ("OUT", "R4"),
    },
    "resolve": {
        "target": ("OUT", "R2"),
        "status": ("INE", "R6"),
        "note": ("INE", "R6"),
        "by": ("INE", "X-HUMAN"),
        "evidence": ("INE", "R6"),
        "project": ("OUT", "R1"),
        "dry_run": ("OUT", "R3"),
    },
    "forget": {
        "target": ("OUT", "R2"),
        "reason": ("INE", "R6"),
        "project": ("OUT", "R1"),
        "dry_run": ("OUT", "R3"),
    },
    "reverify": {
        "target": ("OUT", "R2"),
        "evidence": ("INE", "R6"),
        "project": ("OUT", "R1"),
    },
    "loops": {
        "project": ("OUT", "R1"),
        "stale": ("OUT", "R4"),
    },
    "decide": {
        "project": ("OUT", "R1"),
        "all_projects": ("OUT", "R4"),
    },
    "refute add": {
        "subject": ("INE", "R6"),
        "verdict": ("INE", "R6"),
        "scope": ("INE", "R6"),
        "evidence": ("INE", "R6"),
        "anchor": ("INE", "R6"),
        "revisit_when": ("INE", "R6"),
        "by": ("INE", "X-HUMAN"),
        "ratify": ("INE", "X-HUMAN"),
        "project": ("OUT", "R1"),
        "json": ("INE", "R6"),
    },
    "refute ratify": {
        "refutation_id": ("OUT", "R2"),
        "by": ("INE", "X-HUMAN"),
        "note": ("INE", "R6"),
        "project": ("OUT", "R1"),
        "slug": ("OUT", "R1"),
        "json": ("INE", "R6"),
    },
    "refute revise": {
        "refutation_id": ("OUT", "R2"),
        "subject": ("INE", "R6"),
        "verdict": ("INE", "R6"),
        "scope": ("INE", "R6"),
        "anchor": ("INE", "R6"),
        "revisit_when": ("INE", "R6"),
        "evidence": ("INE", "R6"),
        "by": ("INE", "X-HUMAN"),
        "ratify": ("INE", "X-HUMAN"),
        "project": ("OUT", "R1"),
        "json": ("INE", "R6"),
    },
    "refute overturn": {
        "refutation_id": ("OUT", "R2"),
        "evidence": ("INE", "R6"),
        "note": ("INE", "R6"),
        "by": ("INE", "X-HUMAN"),
        "project": ("OUT", "R1"),
        "slug": ("OUT", "R1"),
        "json": ("INE", "R6"),
    },
    "refute show": {
        "refutation_id": ("OUT", "R2"),
        "project": ("OUT", "R1"),
        "json": ("OUT", "R4"),
    },
    "refute list": {
        "state": ("OUT", "R4"),
        "project": ("OUT", "R1"),
        "json": ("OUT", "R4"),
    },
    "refute search": {
        "query": ("OUT", "R4"),
        "state": ("OUT", "R4"),
        "project": ("OUT", "R1"),
        "json": ("OUT", "R4"),
    },
    "refute guard": {
        "query": ("OUT", "R4"),
        "anchor": ("OUT", "R4"),
        "project": ("OUT", "R1"),
        "json": ("OUT", "R4"),
        "quiet": ("OUT", "R4"),
    },
    "ruling propose": {
        "subject": ("INE", "R6"),
        "verdict": ("INE", "R6"),
        "scope": ("INE", "R6"),
        "evidence": ("INE", "R6"),
        "anchor": ("INE", "R6"),
        "revisit_when": ("INE", "R6"),
        "by": ("INE", "X-HUMAN"),
        "ratify": ("INE", "X-HUMAN"),
        "check_body_file": ("INE", "R6"),
        "check_match": ("INE", "R6"),
        "check_intent": ("INE", "R6"),
        "request_policy": ("INE", "R6"),
        "project": ("OUT", "R1"),
        "json": ("INE", "R6"),
    },
    "ruling ratify": {
        "ruling_id": ("OUT", "R2"),
        "by": ("INE", "X-HUMAN"),
        "note": ("INE", "R6"),
        "project": ("OUT", "R1"),
        "slug": ("OUT", "R1"),
        "json": ("INE", "R6"),
    },
    "ruling revise": {
        "ruling_id": ("OUT", "R2"),
        "subject": ("INE", "R6"),
        "verdict": ("INE", "R6"),
        "scope": ("INE", "R6"),
        "anchor": ("INE", "R6"),
        "revisit_when": ("INE", "R6"),
        "evidence": ("INE", "R6"),
        "by": ("INE", "X-HUMAN"),
        "ratify": ("INE", "X-HUMAN"),
        "check_body_file": ("INE", "R6"),
        "check_match": ("INE", "R6"),
        "check_intent": ("INE", "R6"),
        "request_policy": ("INE", "R6"),
        "no_request_policy": ("INE", "R6"),
        "project": ("OUT", "R1"),
        "json": ("INE", "R6"),
    },
    "ruling retire": {
        "ruling_id": ("OUT", "R2"),
        "evidence": ("INE", "R6"),
        "note": ("INE", "R6"),
        "by": ("INE", "X-HUMAN"),
        "project": ("OUT", "R1"),
        "slug": ("OUT", "R1"),
        "json": ("INE", "R6"),
    },
    "ruling check try": {
        "ruling_id": ("OUT", "R2"),
        "command": ("INE", "R6"),
        "cwd": ("INE", "R6"),
        "proposed": ("INE", "R6"),
        "by": ("INE", "X-HUMAN"),
        "project": ("OUT", "R1"),
    },
    "ruling checks": {
        "project": ("OUT", "R1"),
        "json": ("OUT", "R4"),
    },
    "ruling list": {
        "state": ("OUT", "R4"),
        "project": ("OUT", "R1"),
        "json": ("OUT", "R4"),
        "inherited": ("OUT", "R4"),
    },
    "ruling show": {
        "ruling_id": ("OUT", "R2"),
        "project": ("OUT", "R1"),
        "json": ("OUT", "R4"),
    },
    "amend propose": {
        "item_id": ("OUT", "R2"),
        "change": ("INE", "R6"),
        "evidence": ("INE", "R6"),
        "note": ("INE", "R6"),
        "by": ("INE", "X-HUMAN"),
        "project": ("OUT", "R1"),
    },
    "amend ratify": {
        "amendment_id": ("OUT", "R2"),
        "by": ("INE", "X-HUMAN"),
        "project": ("OUT", "R1"),
        "slug": ("OUT", "R1"),
    },
    "amend reject": {
        "amendment_id": ("OUT", "R2"),
        "note": ("INE", "R6"),
        "by": ("INE", "X-HUMAN"),
        "project": ("OUT", "R1"),
        "slug": ("OUT", "R1"),
    },
    "amend list": {
        "project": ("OUT", "R1"),
        "json": ("OUT", "R4"),
    },
    "trust propose": {
        "text": ("INE", "R6"),
        "kind": ("INE", "R6"),
        "reason": ("INE", "R6"),
        "evidence": ("INE", "R6"),
        "item_id": ("OUT", "R2"),
        "by": ("INE", "X-HUMAN"),
        "project": ("OUT", "R1"),
    },
    "trust confirm": {
        "quarantine_id": ("OUT", "R2"),
        "by": ("INE", "X-HUMAN"),
        "project": ("OUT", "R1"),
    },
    "trust dismiss": {
        "quarantine_id": ("OUT", "R2"),
        "by": ("INE", "X-HUMAN"),
        "project": ("OUT", "R1"),
    },
    "trust release": {
        "quarantine_id": ("OUT", "R2"),
        "by": ("INE", "X-HUMAN"),
        "project": ("OUT", "R1"),
    },
    "trust list": {
        "project": ("OUT", "R1"),
        "json": ("OUT", "R4"),
    },
    "trust repair": {
        "project": ("OUT", "R1"),
        "dry_run": ("OUT", "R3"),
    },
    "trust show": {
        "quarantine_id": ("OUT", "R2"),
        "project": ("OUT", "R1"),
        "json": ("OUT", "R4"),
    },
    "ledger repair": {
        "name": ("INE", "R6"),
        "project": ("OUT", "R1"),
        "dry_run": ("OUT", "R3"),
    },
    "request open": {
        "to": ("INE", "R6"),
        "ask": ("INE", "R6"),
        "why": ("INE", "R6"),
        "to_human": ("INE", "R6"),
        "kind": ("INE", "R6"),
        "blocking": ("INE", "R6"),
        "evidence": ("INE", "R6"),
        "supersedes": ("INE", "R6"),
        "anyway": ("INE", "X-HUMAN"),
        "by": ("INE", "X-HUMAN"),
        "project": ("OUT", "R1"),
    },
    "request revise": {
        "request_id": ("OUT", "R2"),
        "ask": ("INE", "R6"),
        "why": ("INE", "R6"),
        "evidence": ("INE", "R6"),
        "by": ("INE", "X-HUMAN"),
        "project": ("OUT", "R1"),
    },
    "request accept": {
        "request_id": ("OUT", "R2"),
        "note": ("INE", "R6"),
        "by": ("INE", "X-HUMAN"),
        "project": ("OUT", "R1"),
        "slug": ("OUT", "R1"),
    },
    "request reject": {
        "request_id": ("OUT", "R2"),
        "note": ("INE", "R6"),
        "by": ("INE", "X-HUMAN"),
        "project": ("OUT", "R1"),
        "slug": ("OUT", "R1"),
    },
    "request needs-info": {
        "request_id": ("OUT", "R2"),
        "note": ("INE", "R6"),
        "by": ("INE", "X-HUMAN"),
        "project": ("OUT", "R1"),
        "slug": ("OUT", "R1"),
    },
    "request suppress": {
        "request_id": ("OUT", "R2"),
        "note": ("INE", "R6"),
        "by": ("INE", "X-HUMAN"),
        "project": ("OUT", "R1"),
        "slug": ("OUT", "R1"),
    },
    "request done": {
        "request_id": ("OUT", "R2"),
        "evidence": ("INE", "R6"),
        "by": ("INE", "X-HUMAN"),
        "project": ("OUT", "R1"),
    },
    "request reply": {
        "request_id": ("OUT", "R2"),
        "note": ("INE", "R6"),
        "evidence": ("INE", "R6"),
        "by": ("INE", "X-HUMAN"),
        "project": ("OUT", "R1"),
    },
    "request list": {
        "json": ("OUT", "R4"),
        "project": ("OUT", "R1"),
    },
    "request inbox": {
        "json": ("OUT", "R4"),
        "project": ("OUT", "R1"),
    },
    "relations list": {
        "state": ("OUT", "R4"),
        "project": ("OUT", "R1"),
        "json": ("OUT", "R4"),
    },
    "relations show": {
        "relation_id": ("OUT", "R2"),
        "project": ("OUT", "R1"),
        "json": ("OUT", "R4"),
    },
    "relations confirm": {
        "relation_id": ("OUT", "R2"),
        "project": ("OUT", "R1"),
    },
    "relations reject": {
        "relation_id": ("OUT", "R2"),
        "project": ("OUT", "R1"),
    },
    "relations retract": {
        "relation_id": ("OUT", "R2"),
        "project": ("OUT", "R1"),
    },
    "handoff": {
        "text": ("INE", "R6"),
        "clear": ("INE", "R6"),
        "project": ("OUT", "R1"),
    },
    "log": {
        "text": ("INE", "R6"),
        "kind": ("INE", "R6"),
        "status": ("INE", "R6"),
        "project": ("OUT", "R1"),
    },
    "recall-inject": {
        "project": ("OUT", "R1"),
        "session": ("OUT", "R4"),
    },
    "action-recall": {
        "project": ("OUT", "R1"),
        "session": ("OUT", "R4"),
        "record_only": ("OUT", "R4"),
    },
    "request-inject": {
        "project": ("OUT", "R1"),
        "session": ("OUT", "R4"),
    },
    "status": {
        "project": ("OUT", "R1"),
        "json": ("OUT", "R4"),
        "suppressed": ("OUT", "R4"),
    },
    "verify-receipt": {
        "session_id": ("OUT", "R2"),
        "project": ("OUT", "R1"),
    },
    "audit quotes": {
        "project": ("OUT", "R1"),
        "all": ("OUT", "R4"),
        "top": ("OUT", "R4"),
        "json": ("OUT", "R4"),
    },
    "audit privacy": {
        "project": ("OUT", "R1"),
        "all_projects": ("OUT", "R4"),
    },
    "audit-quotes": {
        "project": ("OUT", "R1"),
        "all": ("OUT", "R4"),
        "top": ("OUT", "R4"),
    },
    "heal": {
        "dry_run": ("OUT", "R3"),
        "force": ("INE", "R6"),
    },
    "team init": {
        "remote_url": ("INE", "R6"),
    },
    "team sync": {
        "project": ("OUT", "R1"),
        "apply_forget": ("INE", "R6"),
    },
    "team status": {
        "json": ("OUT", "R4"),
    },
    "configure": {
        "backend": ("INE", "R6"),
        "api_key": ("INE", "R6"),
        "model": ("INE", "R6"),
        "base_url": ("INE", "R6"),
        "command": ("INE", "R6"),
        "output": ("INE", "R6"),
        "input": ("INE", "R6"),
        "init": ("INE", "R6"),
        "timeout": ("INE", "R6"),
        "author": ("INE", "R6"),
        "team_remote": ("INE", "R6"),
        "test": ("INE", "R6"),
    },
    "stats": {
        "json": ("OUT", "R4"),
    },
    "check sync": {
        "check": ("OUT", "R4"),
        "json": ("OUT", "R4"),
        "project": ("OUT", "R1"),
    },
    "hooks list": {
    },
    "hooks status": {
        "json": ("OUT", "R4"),
    },
    "hooks install": {
        "host": ("INE", "R6"),
        "all": ("INE", "R6"),
    },
    "hooks remove": {
        "host": ("INE", "R6"),
        "all": ("INE", "R6"),
    },
    "skill list": {
    },
    "skill show": {
        "compact": ("OUT", "R4"),
    },
    "skill status": {
        "json": ("OUT", "R4"),
    },
    "skill install": {
        "host": ("INE", "R6"),
        "project": ("OUT", "R1"),
        "all": ("INE", "R6"),
    },
    "skill uninstall": {
        "host": ("INE", "R6"),
        "project": ("OUT", "R1"),
        "all": ("INE", "R6"),
    },
    "mcp serve": {
    },
}
